veslo_app:
    http:
        client:
            logging: '%app.http_client.logging%'
            headers:
                user_agent: '%app.http_client.headers.user_agent%'
            proxy:
                enabled: '%app.http_client.proxy.enabled%'
                static_list: '%app.http_client.proxy.static_list%'
    amqp_client:
        host: '%app.amqp_client.host%'
        vhost: '%app.amqp_client.vhost%'
        user: '%app.amqp_client.user%'
        password: '%app.amqp_client.password%'
        heartbeat: '%app.amqp_client.heartbeat%'
    workflow:
        vacancy_research:
            transitions:
                queue_prefix: 'veslo.app.workflow.vacancy_research.'
