veslo_sanity:
    vacancy:
        analyser:
            # Locale which will be used as a default sanity data translation locale
            default_locale: '%locale%'
            # All locales which are supported for sanity data translations
            locales:
                - 'ru'
