veslo_anthill:
    vacancy:
        digging:
            roadmap:
                # How much vacancy search attempts cranky dung beetle should perform via roadmap before give up
                attempts_until_pause: 3
                # Give up time in seconds for cranky dung beetle after too much unsuccessful vacancy search attempts
                pause_duration: 120
        # Options for vacancy providers
        provider:
            # Vacancies count per page for rendering during list action
            per_page: 10
        # Options for vacancy repository
        repository:
            # Query result cache namespace for vacancy repository
            cache_result_namespace: 'veslo.anthill.vacancy_repository.'
            # How long query result cache will be available after successful put,
            # during this time some data changes on website will not be seen, for example, vacancy list
            cache_result_lifetime: 300
