imports:
    - { resource: config.yml }

framework:
    router:
        resource: '%kernel.project_dir%/app/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            max_files: 1
            level: debug
            channels:
                - '!event'
                - '!app.http'
                - '!app.workflow'
                - '!anthill.digging'
                - '!anthill.parsing'
                - '!anthill.collecting'
                - '!sanity.indexing'
        app.http:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.app.http.log'
            max_files: 1
            level: debug
            channels:
                - 'app.http'
        app.workflow:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.app.workflow.log'
            max_files: 1
            level: debug
            channels:
                - 'app.workflow'
        anthill.digging:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.anthill.digging.log'
            max_files: 1
            level: debug
            channels:
                - 'anthill.digging'
        anthill.parsing:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.anthill.parsing.log'
            max_files: 1
            level: debug
            channels:
                - 'anthill.parsing'
        anthill.collecting:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.anthill.collecting.log'
            max_files: 1
            level: debug
            channels:
                - 'anthill.collecting'
        sanity.indexing:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.sanity.indexing.log'
            max_files: 1
            level: debug
            channels:
                - 'sanity.indexing'
        console:
            type: console
            process_psr_3_messages: false
            channels:
                - '!event'
                - '!doctrine'
                - '!console'
        # To follow logs in real time, execute the following command:
        # `bin/console server:log -vv`
        #server_log:
        #    type: server_log
        #    process_psr_3_messages: false
        #    host: 127.0.0.1:9911
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info

#swiftmailer:
#    delivery_addresses: ['me@example.com']

twig:
    strict_variables: true
    auto_reload: true
