doctrine:
    orm:
        default_entity_manager: anthill
        entity_managers:
            anthill:
                connection: anthill
                naming_strategy: doctrine.orm.naming_strategy.underscore
                default_repository_class: Veslo\AppBundle\Entity\Repository\BaseRepository
                metadata_cache_driver:
                    type: predis
                    host: '%app.redis.host%'
                    port: '%app.redis.port%'
                    database: 1
                result_cache_driver:
                    cache_provider: doctrine.orm.anthill_metadata_cache
                query_cache_driver:
                    cache_provider: doctrine.orm.anthill_metadata_cache
                mappings:
                    # is_bundle is considered a legacy option, so we use "Outside of a Bundle" style
                    # all bundles can potentially be moved to project dependencies category
                    # https://symfony.com/doc/current/reference/configuration/doctrine.html#is-bundle
                    VesloAnthillBundle:
                        type: annotation
                        dir: '%kernel.project_dir%/src/AnthillBundle/Entity'
                        prefix: Veslo\AnthillBundle\Entity
                        alias: VesloAnthill
    dbal:
        default_connection: anthill
        connections:
            anthill:
                driver: pdo_pgsql
                host: '%doctrine.dbal.connections.anthill.database_host%'
                port: '%doctrine.dbal.connections.anthill.database_port%'
                dbname: '%doctrine.dbal.connections.anthill.database_name%'
                user: '%doctrine.dbal.connections.anthill.database_user%'
                password: '%doctrine.dbal.connections.anthill.database_password%'
                charset: UTF8

doctrine_migrations:
    dir_name: "%kernel.root_dir%/Resources/migrations/doctrine"
    namespace: Veslo\Migrations
    table_name: migration_versions
    name: Application Migrations
    organize_migrations: false # Version >= 1.2, possible values are: "BY_YEAR", "BY_YEAR_AND_MONTH", false
    custom_template: ~ # Version >= 1.2, path to your custom migrations template
