doctrine:
    orm:
        default_entity_manager: anthill
        entity_managers:
            anthill:
                connection: anthill
                naming_strategy: doctrine.orm.naming_strategy.underscore
                default_repository_class: Veslo\AppBundle\Entity\Repository\BaseEntityRepository
                metadata_cache_driver:
                    type: predis
                    host: '%app.redis.host%'
                    port: '%app.redis.port%'
                    database: 1
                result_cache_driver:
                    cache_provider: doctrine.orm.anthill_metadata_cache
                query_cache_driver:
                    cache_provider: doctrine.orm.anthill_metadata_cache
                second_level_cache:
                    region_cache_driver:
                        cache_provider: doctrine.orm.anthill_metadata_cache
                    region_lifetime: 14400
                    regions:
                        roadmap_parameters_head_hunter:
                            type: filelock
                            cache_driver:
                                type: predis
                                host: '%app.redis.host%'
                                port: '%app.redis.port%'
                                database: 2
                        vacancies:
                            type: default
                            cache_driver:
                                type: predis
                                host: '%app.redis.host%'
                                port: '%app.redis.port%'
                                database: 3
                            lifetime: '%anthill.vacancies.cache_lifetime%'
                        history:
                            type: default
                            cache_driver:
                                type: predis
                                host: '%app.redis.host%'
                                port: '%app.redis.port%'
                                database: 4
                mappings:
                    # is_bundle is considered a legacy option, so we use "Outside of a Bundle" style
                    # all bundles can potentially be moved to project dependencies category
                    # https://symfony.com/doc/current/reference/configuration/doctrine.html#is-bundle
                    VesloAnthillBundle:
                        type: annotation
                        dir: '%kernel.project_dir%/src/AnthillBundle/Entity'
                        prefix: Veslo\AnthillBundle\Entity
                        alias: VesloAnthill
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
            sanity:
                connection: sanity
                naming_strategy: doctrine.orm.naming_strategy.underscore
                default_repository_class: Veslo\AppBundle\Entity\Repository\BaseEntityRepository
                metadata_cache_driver:
                    type: predis
                    host: '%app.redis.host%'
                    port: '%app.redis.port%'
                    database: 5
                result_cache_driver:
                    cache_provider: doctrine.orm.sanity_metadata_cache
                query_cache_driver:
                    cache_provider: doctrine.orm.sanity_metadata_cache
                second_level_cache:
                    region_cache_driver:
                        cache_provider: doctrine.orm.sanity_metadata_cache
                    region_lifetime: 14400
                    regions:
                        index:
                            type: default
                            cache_driver:
                                type: predis
                                host: '%app.redis.host%'
                                port: '%app.redis.port%'
                                database: 6
                            lifetime: 0
                mappings:
                    VesloSanityBundle:
                        type: annotation
                        dir: '%kernel.project_dir%/src/SanityBundle/Entity'
                        prefix: Veslo\SanityBundle\Entity
                        alias: VesloSanity
    dbal:
        default_connection: anthill
        connections:
            anthill:
                driver: pdo_pgsql
                host: '%doctrine.dbal.connections.anthill.database_host%'
                port: '%doctrine.dbal.connections.anthill.database_port%'
                dbname: '%doctrine.dbal.connections.anthill.database_name%'
                user: '%doctrine.dbal.connections.anthill.database_user%'
                password: '%doctrine.dbal.connections.anthill.database_password%'
                charset: UTF8
                # Preserve schema from other entity managers in the same database.
                # https://symfony.com/doc/master/bundles/DoctrineMigrationsBundle/index.html#manual-tables
                schema_filter: ~^(?!sanity_)~
            sanity:
                driver: pdo_pgsql
                host: '%doctrine.dbal.connections.sanity.database_host%'
                port: '%doctrine.dbal.connections.sanity.database_port%'
                dbname: '%doctrine.dbal.connections.sanity.database_name%'
                user: '%doctrine.dbal.connections.sanity.database_user%'
                password: '%doctrine.dbal.connections.sanity.database_password%'
                charset: UTF8
                schema_filter: ~^(?!anthill_)~

doctrine_migrations:
    dir_name: "%kernel.root_dir%/Resources/migrations/doctrine"
    namespace: Veslo\Migrations
    table_name: migration_versions
    name: Application Migrations
    organize_migrations: false # Version >= 1.2, possible values are: "BY_YEAR", "BY_YEAR_AND_MONTH", false
    custom_template: ~ # Version >= 1.2, path to your custom migrations template

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        anthill:
            sluggable: true
            timestampable: true
            loggable: true
            softdeleteable: true
