services:
    # Configurations
    veslo.anthill.vacancy.roadmap.configuration.head_hunter:
        class: Veslo\AnthillBundle\Vacancy\Roadmap\Configuration\HeadHunter
        arguments:
            - '@serializer'
            - '@monolog.logger.anthill.digging'
            - '@veslo.anthill.vacancy.roadmap.configuration.parameters.head_hunter_repository'

    # Roadmap
    veslo.anthill.vacancy.roadmap.head_hunter:
        class: Veslo\AnthillBundle\Vacancy\Roadmap\BaseConfigurableRoadmap
        arguments:
            - '@veslo.anthill.vacancy.roadmap.strategy.head_hunter.api.version20190213'
            - '@veslo.anthill.vacancy.roadmap.configuration.head_hunter'
        tags:
            -   name: !php/const Veslo\AnthillBundle\Vacancy\RoadmapInterface::TAG
                roadmapName: !php/const Veslo\AnthillBundle\Enum\Vacancy\Roadmap::HEAD_HUNTER

    # Search strategies
    veslo.anthill.vacancy.roadmap.strategy.head_hunter.api.version20190213:
        class: Veslo\AnthillBundle\Vacancy\Roadmap\Strategy\HeadHunter\Api\Version20190213
        arguments:
            - '@monolog.logger.anthill.digging'
            - '@veslo.app.http_client'
            - '@serializer.encoder.json'

    # Scanner
    veslo.anthill.vacancy.scanner.head_hunter:
        class: Veslo\AnthillBundle\Vacancy\Scanner\MultistrategicScanner
        arguments:
            - '@veslo.anthill.vacancy.scanner.strategy_pool.head_hunter'
        tags:
            -   name: !php/const Veslo\AnthillBundle\Vacancy\ScannerInterface::TAG
                roadmapName: !php/const Veslo\AnthillBundle\Enum\Vacancy\Roadmap::HEAD_HUNTER

    # Scanner strategy pool
    veslo.anthill.vacancy.scanner.strategy_pool.head_hunter:
        class: Veslo\AnthillBundle\Vacancy\Scanner\StrategyPool\OneToOneStrategyPool
        arguments:
            -   Strategy\HeadHunter\Api\Version20190213: '@veslo.anthill.vacancy.scanner.strategy.head_hunter.api.version20190213'

    # Parse strategies
    veslo.anthill.vacancy.scanner.strategy.head_hunter.api.version20190213:
        class: Veslo\AnthillBundle\Vacancy\Scanner\Strategy\HeadHunter\Api\Version20190213
