services:
    # HeadHunter
    veslo.anthill.vacancy.roadmap.head_hunter:
        class: Veslo\AnthillBundle\Vacancy\Roadmap\BaseConfigurableRoadmap
        arguments:
            - '@veslo.anthill.vacancy.roadmap.strategy.head_hunter.api.version20190213'
            - '@veslo.anthill.vacancy.roadmap.configuration.head_hunter'
        tags:
            -   name: !php/const Veslo\AnthillBundle\Vacancy\RoadmapInterface::TAG
                roadmapName: !php/const Veslo\AnthillBundle\Enum\Vacancy\Roadmap::HEAD_HUNTER

    # Configurations
    veslo.anthill.vacancy.roadmap.configuration.head_hunter:
        class: Veslo\AnthillBundle\Vacancy\Roadmap\Configuration\HeadHunter
        arguments:
            - '@veslo.anthill.vacancy.roadmap.configuration.parameters.head_hunter_repository'

    # Search strategies
    veslo.anthill.vacancy.roadmap.strategy.head_hunter.api.version20190213:
        class: Veslo\AnthillBundle\Vacancy\Roadmap\Strategy\HeadHunter\Api\Version20190213
        arguments:
            - '@monolog.logger.anthill.digging'
            - '@veslo.app.http_client'
            - '@serializer.encoder.json'

    # TODO: Parsers
#    veslo.anthill.vacancy.roadmap.parser.head_hunter.api.version20190213:
#        strategyName="Strategy\HeadHunter\Api\Version20190213"
