services:
    # Provides a proxy list from predefined array
    # TODO: or dynamically by fetching URI, with predefined array as a fallback (see DI extension)
    veslo.app.http.proxy.locator:
        alias: 'veslo.app.http.proxy.locator.static_array_locator'

    # 50
    # cache_locator

    # 25
    veslo.app.http.proxy.locator.uri_locator:
        class: Veslo\AppBundle\Http\Proxy\Locator\UriLocator
        lazy: true
        arguments:
            - '@serializer'
            - '%veslo.app.http.client.proxy.locator.uri_locator.options%'

    # -100
    veslo.app.http.proxy.locator.static_array_locator:
        class: Veslo\AppBundle\Http\Proxy\Locator\StaticArrayLocator
        lazy: true
        arguments:
            - '%veslo.app.http.client.proxy.static_list%'
