services:
    veslo.app.http_client:
        class: GuzzleHttp\Client
        arguments:
            - '%veslo.app.http_client.config%'

    veslo.app.amqp_client:
        class: Bunny\Client
        arguments:
            - '%veslo.app.amqp_client.options%'

    veslo.app.workflow.vacancy.research.marking_store:
        class: Veslo\AppBundle\Workflow\Vacancy\Research\MarkingStore

    veslo.app.workflow.vacancy.research.conveyor:
        class: Veslo\AppBundle\Workflow\Vacancy\Research\Conveyor
        arguments:
            - '@workflow.vacancy_research'
            - '@serializer'
            - '@veslo.app.amqp_client'
            - '%veslo.app.workflow.vacancy_research.transitions.queue_prefix%'
