services:
    veslo.app.http_client:
        class: GuzzleHttp\Client
        arguments:
            - '%veslo.app.http_client.config%'

    veslo.app.amqp_client:
        class: Bunny\Client
        arguments:
            - '%veslo.app.amqp_client.options%'

    veslo.app.workflow.vacancy.research.marking_store:
        class: Veslo\AppBundle\Workflow\Vacancy\Research\MarkingStore

    veslo.app.workflow.vacancy.research.conveyor:
        class: Veslo\AppBundle\Workflow\Vacancy\Research\Conveyor
        arguments:
            - '@monolog.logger.app.workflow'
            - '@workflow.vacancy_research'
            - '@serializer'
            - '@veslo.app.amqp_client'
            - '%veslo.app.workflow.vacancy_research.transitions.queue_prefix%'

    veslo.app.menu.builder:
        class: Veslo\AppBundle\Menu\Builder
        arguments:
            - '@knp_menu.factory'
            - '@event_dispatcher'
        tags:
            -   name: knp_menu.menu_builder
                method: createMainMenu
                alias: main
