services:
    app.twig.extension.text:
        class: Twig\Extensions\TextExtension
        tags:
            - 'twig.extension'

    app.twig.extension.intl:
        class: Twig\Extensions\IntlExtension
        tags:
            - 'twig.extension'

    app.twig.extension.strip_attributes:
        class: Veslo\AppBundle\Twig\Extension\StripAttributesExtension
        tags:
            - 'twig.extension'
