services:
    veslo.sanity.vacancy.analyser.ministry_of_truth:
        class: Veslo\SanityBundle\Vacancy\Analyser\MinistryOfTruth
        arguments:
            - '@symfony_doge.motc.client'
            - '@symfony_doge.motc.credentials.storage'
            - '@veslo.sanity.vacancy.analyser.ministry_of_truth.data_converter'
            - '%veslo.sanity.vacancy.analyser.ministry_of_truth.options%'

    veslo.sanity.vacancy.analyser.ministry_of_truth.data_converter:
        class: Veslo\SanityBundle\Vacancy\Analyser\MinistryOfTruth\DataConverter
