services:
    veslo.sanity.vacancy.indexer.cockroach:
        class: Veslo\SanityBundle\Vacancy\Indexer\Cockroach
        arguments:
            - '@monolog.logger.sanity.indexing'
            - '@veslo.anthill.vacancy_repository'
            - '@veslo.sanity.vacancy.analyser.ministry_of_truth'
            - '@veslo.sanity.vacancy.index.creator'
            - '@serializer'
