services:
    veslo.anthill.command.roadmap.list:
        class: Veslo\AnthillBundle\Command\Roadmap\ListCommand
        arguments:
            - '@veslo.anthill.vacancy.ant_queen'
        tags:
            - { name: 'console.command', command: 'veslo:anthill:roadmap:list' }

    veslo.anthill.command.digging:
        class: Veslo\AnthillBundle\Command\DiggingCommand
        arguments:
            - '@veslo.anthill.vacancy.ant_queen'
            - '@veslo.anthill.vacancy.digger.cranky_dung_beetle'
        tags:
            - { name: 'console.command', command: 'veslo:anthill:digging' }

    veslo.anthill.command.parsing:
        class: Veslo\AnthillBundle\Command\ParsingCommand
        arguments:
            - '@veslo.anthill.vacancy.parser.earwig'
            - '@veslo.anthill.vacancy.dung_pit'
        tags:
            - { name: 'console.command', command: 'veslo:anthill:parsing' }
