services:
    veslo.anthill.vacancy_controller:
        class: Veslo\AnthillBundle\Controller\VacancyController
        public: true
        arguments:
            - '@templating'
            - '@veslo.anthill.vacancy.provider.journal'
            - '@veslo.anthill.vacancy.provider.archive'
            - '@veslo.sanity.vacancy.index_repository'
