services:
    veslo.anthill.vacancy.dung_pit:
        class: Veslo\AnthillBundle\Vacancy\DungPit
        arguments:
            - '@veslo.app.workflow.vacancy.research.conveyor'
            - 'Veslo\AnthillBundle\Dto\Vacancy\LocationDto'

    veslo.anthill.vacancy.chewed_dung_pit:
        class: Veslo\AnthillBundle\Vacancy\DungPit
        arguments:
            - '@veslo.app.workflow.vacancy.research.conveyor'
            - 'Veslo\AnthillBundle\Dto\Vacancy\Parser\ParsedDto'

    veslo.anthill.vacancy.sinful_dung_pit:
        class: Veslo\AnthillBundle\Vacancy\DungPit
        arguments:
            - '@veslo.app.workflow.vacancy.research.conveyor'
            - 'Veslo\AnthillBundle\Dto\Vacancy\Collector\AcceptanceDto'
