services:
    veslo.anthill.vacancy.roadmap.configuration.parameters.head_hunter_repository:
        class: Veslo\AnthillBundle\Entity\Repository\Vacancy\Roadmap\Configuration\Parameters\HeadHunterRepository
        factory: ['@doctrine.orm.anthill_entity_manager', getRepository]
        arguments:
            - 'Veslo\AnthillBundle\Entity\Vacancy\Roadmap\Configuration\Parameters\HeadHunter'

    veslo.anthill.vacancy_repository:
        class: Veslo\AnthillBundle\Entity\Repository\VacancyRepository
        factory: ['@doctrine.orm.anthill_entity_manager', getRepository]
        arguments:
            - 'Veslo\AnthillBundle\Entity\Vacancy'

    veslo.anthill.company_repository:
        class: Veslo\AppBundle\Entity\Repository\BaseEntityRepository
        factory: ['@doctrine.orm.anthill_entity_manager', getRepository]
        arguments:
            - 'Veslo\AnthillBundle\Entity\Company'

    veslo.anthill.vacancy.category_repository:
        class: Veslo\AppBundle\Entity\Repository\BaseEntityRepository
        factory: ['@doctrine.orm.anthill_entity_manager', getRepository]
        arguments:
            - 'Veslo\AnthillBundle\Entity\Vacancy\Category'
