services:
    veslo.anthill.vacancy.roadmap.head_hunter:
        class: Veslo\AnthillBundle\Vacancy\Roadmap\BaseConfigurableRoadmap
        arguments:
            - '@veslo.anthill.vacancy.roadmap.strategy.query'
        tags:
            -
                name: !php/const Veslo\AnthillBundle\Vacancy\RoadmapInterface::TAG
                roadmapName: !php/const Veslo\AnthillBundle\Enum\Vacancy\Roadmap::HEAD_HUNTER
