anthill_vacancy_index:
    path: /
    defaults:
        _controller: veslo.anthill.vacancy_controller:listAction
        page: 1
    methods:
        - GET

anthill_vacancy_list:
    path: /vacancies/page/{page}
    defaults:
        _controller: veslo.anthill.vacancy_controller:listAction
    methods:
        - GET
    requirements:
        page: \d+

anthill_vacancy_show:
    path: /vacancy/{slug}
    defaults:
        _controller: veslo.anthill.vacancy_controller:showAction
    methods:
        - GET
    requirements:
        slug: \d+\-.+
