anthill_vacancy_index:
    path: /
    defaults:
        _controller: veslo.anthill.vacancy_controller:list
        page: 1
    methods:
        - GET

anthill_vacancy_list_page:
    path: /vacancies/page/{page}
    defaults:
        _controller: veslo.anthill.vacancy_controller:list
    methods:
        - GET
    requirements:
        page: \d+

anthill_vacancy_list_by_category:
    path: /category/{categoryName}
    defaults:
        _controller: veslo.anthill.vacancy_controller:listByCategory
        page: 1
    methods:
        - GET

anthill_vacancy_list_by_category_page:
    path: /category/{categoryName}/page/{page}
    defaults:
        _controller: veslo.anthill.vacancy_controller:listByCategory
    methods:
        - GET
    requirements:
        page: \d+

anthill_vacancy_archive:
    path: /archive
    defaults:
        _controller: veslo.anthill.vacancy_controller:listArchive
        page: 1
    methods:
        - GET

anthill_vacancy_archive_page:
    path: /archive/page/{page}
    defaults:
        _controller: veslo.anthill.vacancy_controller:listArchive
    methods:
        - GET
    requirements:
        page: \d+

anthill_vacancy_show:
    path: /vacancy/{vacancySlug}
    defaults:
        _controller: veslo.anthill.vacancy_controller:show
    methods:
        - GET
    requirements:
        vacancySlug: \d+\-.+
