anthill_vacancy_index:
    path: /
    defaults:
        _controller: veslo.anthill.vacancy_controller:list
        page: 1
    methods:
        - GET

anthill_vacancy_list:
    path: /vacancies/page/{page}
    defaults:
        _controller: veslo.anthill.vacancy_controller:list
    methods:
        - GET
    requirements:
        page: \d+

anthill_vacancy_show:
    path: /vacancy/{vacancySlug}
    defaults:
        _controller: veslo.anthill.vacancy_controller:show
    methods:
        - GET
    requirements:
        vacancySlug: \d+\-.+
