services:
    veslo.anthill.vacancy.ant_queen:
        class: Veslo\AnthillBundle\Vacancy\AntQueen

    veslo.anthill.vacancy.digger.cranky_dung_beetle:
        class: Veslo\AnthillBundle\Vacancy\Digger\CrankyDungBeetle
        arguments:
            - '@veslo.anthill.vacancy.digger.dung_beetle'
            - '@cache.app'
            - '%veslo.anthill.vacancy.digging.roadmap.attempts_until_pause%'
            - '%veslo.anthill.vacancy.digging.roadmap.pause_duration%'

    veslo.anthill.vacancy.digger.dung_beetle:
        class: Veslo\AnthillBundle\Vacancy\Digger\DungBeetle
        arguments:
            - '@monolog.logger.anthill.digging'
            - '@veslo.anthill.vacancy.dung_pit'

    veslo.anthill.vacancy.parser.earwig:
        class: Veslo\AnthillBundle\Vacancy\Parser\Earwig
        arguments:
            - '@monolog.logger.anthill.parsing'
            - '@veslo.anthill.vacancy.scan_result_normalizer'
            - '@veslo.anthill.vacancy.scanner_pool.conveyor_aware_scanner_pool'
            - '@veslo.anthill.vacancy.chewed_dung_pit'

    veslo.anthill.vacancy.collector.ant_worker:
        class: Veslo\AnthillBundle\Vacancy\Collector\AntWorker
        arguments:
            - '@monolog.logger.anthill.collecting'
            - '@veslo.anthill.vacancy.acceptance_normalizer'
            - '@veslo.anthill.vacancy.decision.is_collectable'
            - '@veslo.anthill.vacancy.creator'
            - '@veslo.anthill.vacancy.dung_pit'

    veslo.anthill.vacancy.dung_pit:
        class: Veslo\AnthillBundle\Vacancy\DungPit
        arguments:
            - '@veslo.app.workflow.vacancy.research.conveyor'
            - 'Veslo\AnthillBundle\Dto\Vacancy\LocationDto'

    veslo.anthill.vacancy.chewed_dung_pit:
        class: Veslo\AnthillBundle\Vacancy\DungPit
        arguments:
            - '@veslo.app.workflow.vacancy.research.conveyor'
            - 'Veslo\AnthillBundle\Dto\Vacancy\Parser\ParsedDto'

    veslo.anthill.vacancy.sinful_dung_pit:
        class: Veslo\AnthillBundle\Vacancy\DungPit
        arguments:
            - '@veslo.app.workflow.vacancy.research.conveyor'
            - 'Veslo\AnthillBundle\Dto\Vacancy\Collector\AcceptanceDto'

    veslo.anthill.vacancy.scanner_pool.conveyor_aware_scanner_pool:
        class: Veslo\AnthillBundle\Vacancy\ScannerPool\ConveyorAwareScannerPool
        arguments:
            - '@veslo.anthill.vacancy.scanner_pool.unique_scanner_pool'

    veslo.anthill.vacancy.scanner_pool.unique_scanner_pool:
        class: Veslo\AnthillBundle\Vacancy\ScannerPool\UniqueScannerPool

    veslo.anthill.vacancy.decision.is_collectable:
        class: Veslo\AnthillBundle\Vacancy\Decision\ChainDecision
        arguments:
            - ['@veslo.anthill.vacancy.decision.not_duplicate']

    veslo.anthill.vacancy.decision.not_duplicate:
        class: Veslo\AnthillBundle\Vacancy\Decision\NotADuplicate
        arguments:
            - '@logger'
            - '@veslo.anthill.vacancy_repository'

    veslo.anthill.vacancy.acceptance_normalizer:
        class: Veslo\AnthillBundle\Vacancy\Normalizer\AcceptanceNormalizer
        arguments:
            - '@veslo.anthill.vacancy.scan_result_normalizer'

    veslo.anthill.vacancy.scan_result_normalizer:
        class: Veslo\AnthillBundle\Vacancy\Normalizer\ScanResultNormalizer
        arguments:
            - '@serializer'

    veslo.anthill.vacancy.provider.journal:
        class: Veslo\AnthillBundle\Vacancy\Provider\Journal
        arguments:
            - '@veslo.anthill.vacancy_repository'
            - '@knp_paginator'
            - '%veslo.anthill.vacancy.provider.options%'

    veslo.anthill.vacancy.creator:
        class: Veslo\AnthillBundle\Vacancy\Creator
        arguments:
            - '@veslo.anthill.company.creator'
            - '@veslo.anthill.vacancy.category.creator'
            - '@veslo.anthill.vacancy_repository'
            - '@veslo.anthill.company_repository'
            - '@veslo.anthill.vacancy.category_repository'

    veslo.anthill.company.creator:
        class: Veslo\AnthillBundle\Company\Creator
        arguments:
            - '@veslo.anthill.company_repository'

    veslo.anthill.vacancy.category.creator:
        class: Veslo\AnthillBundle\Vacancy\Category\Creator
        arguments:
            - '@veslo.anthill.vacancy.category_repository'
