services:
    veslo.anthill.vacancy.decision.is_collectable:
        class: Veslo\AnthillBundle\Vacancy\Decision\ChainDecision
        arguments:
            - ['@veslo.anthill.vacancy.decision.not_duplicate']

    veslo.anthill.vacancy.decision.not_duplicate:
        class: Veslo\AnthillBundle\Vacancy\Decision\NotADuplicate
        arguments:
            - '@logger'
            - '@veslo.anthill.vacancy_repository'
